version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/src/main/resources/postgresql"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/src/main/resources/postgresql/data
    ports:
      - "5432:5432"